version: "3"

services:
  web:
    container_name: web_app
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./animenz:/site/animenz

  ubuntu:
    container_name: ubuntu_container
    image: ubuntu