# Generated by Django 4.1 on 2022-08-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheets',
            new_name='Sheet',
        ),
    ]
