# Generated by Django 4.1 on 2022-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_rename_sheets_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(default='adfgadfga', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='tags',
            field=models.ManyToManyField(related_name='post', to='sheets.tag'),
        ),
    ]
