# Generated by Django 4.1 on 2022-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_tag_sheet_slug_sheet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
