# Generated by Django 4.1 on 2022-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='first_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
