# Generated by Django 4.1 on 2022-08-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_alter_sheet_file_alter_sheet_first_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='first_photo',
            new_name='photo',
        ),
    ]
