# Generated by Django 4.1 on 2022-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_rename_first_photo_sheet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
