# Generated by Django 4.1 on 2022-09-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_category_sheet_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['name'], 'verbose_name': 'Sheet', 'verbose_name_plural': 'Sheets'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
